/**
 * Generates an idempotent UPSERT script from seed/candidates.json and applies it
 * to D1 via wrangler.
 *
 *   bun run seed:local     # .wrangler/state miniflare D1
 *   bun run seed:staging   # the anon-vote-sys-staging database
 *   bun run seed:remote    # the real production database
 *
 * Extra flags:
 *   --prune   also DELETE candidates that are no longer in the JSON file.
 *             Their votes go with them (ON DELETE CASCADE), so this is off by default.
 *   --dry     print the SQL instead of executing it.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import candidatesFile from "./candidates.json" with { type: "json" };
const IMAGE_BASE_URL = "https://cdn.jsdelivr.net/gh/Madiocre/vote-images/";

const HERE = import.meta.dirname;
const PKG_ROOT = resolve(HERE, "..");
const WRANGLER_CONFIG = resolve(PKG_ROOT, "../../apps/web/wrangler.jsonc");
const OUT_DIR = join(PKG_ROOT, ".generated");
const OUT_FILE = join(OUT_DIR, "seed.sql");

interface SeedCandidate {
  id: string;
  name: string;
  imageUrl: string;
  sortOrder?: number;
}

const args = new Set(process.argv.slice(2));
const staging = args.has("--staging");
// --staging implies remote: the staging D1 only exists on Cloudflare.
const remote = args.has("--remote") || staging;
const local = !remote;
const prune = args.has("--prune");
const dry = args.has("--dry");

// Named environments deploy as `<name>-<env>`, and their D1 is a genuinely
// separate database — see the `env.staging` block in apps/web/wrangler.jsonc.
const DB_NAME = staging ? "anon-vote-sys-staging" : "anon-vote-sys";
const ENV_FLAGS = staging ? ["--env", "staging"] : [];

/** SQLite string literal: single quotes doubled, wrapped in quotes. */
function q(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function validate(candidates: SeedCandidate[]): void {
  if (candidates.length === 0) throw new Error("seed/candidates.json contains no candidates.");

  const seen = new Set<string>();
  for (const candidate of candidates) {
    if (!candidate.id?.trim()) throw new Error(`A candidate is missing "id".`);
    if (!candidate.name?.trim()) throw new Error(`Candidate "${candidate.id}" is missing "name".`);
    if (!candidate.imageUrl?.trim()) throw new Error(`Candidate "${candidate.id}" is missing "imageUrl".`);
    if (seen.has(candidate.id)) throw new Error(`Duplicate candidate id: "${candidate.id}".`);
    seen.add(candidate.id);
  }
}

function buildSql(candidates: SeedCandidate[]): string {
  const lines: string[] = [
    "-- Generated by packages/db/seed/seed.ts. Do not edit by hand.",
    "",
  ];

  candidates.forEach((candidate, index) => {
    const sortOrder = candidate.sortOrder ?? index + 1;
    // created_at has to be supplied explicitly. schema.ts declares it with
    // Drizzle's .$defaultFn(), which is an APPLICATION-level default the query
    // builder fills in — the generated DDL is a bare `integer NOT NULL` with no
    // SQL DEFAULT, so raw SQL like this would hit a NOT NULL violation.
    // unixepoch() matches Drizzle's { mode: "timestamp" }, which is seconds.
    // Deliberately absent from the DO UPDATE list below: re-seeding refreshes
    // name/image/order but must not rewrite when the candidate first appeared.
    lines.push(
      `INSERT INTO candidates (id, name, image_url, sort_order, created_at) VALUES (${q(
        candidate.id,
      )}, ${q(candidate.name)}, ${q(IMAGE_BASE_URL + candidate.imageUrl)}, ${sortOrder}, unixepoch())`,
      `  ON CONFLICT(id) DO UPDATE SET name = excluded.name, image_url = excluded.image_url, sort_order = excluded.sort_order;`,
    );
  });

  if (prune) {
    const keep = candidates.map((candidate) => q(candidate.id)).join(", ");
    lines.push("", `DELETE FROM candidates WHERE id NOT IN (${keep});`);
  }

  return lines.join("\n") + "\n";
}

const candidates = (candidatesFile as { candidates: SeedCandidate[] }).candidates;
validate(candidates);

const sql = buildSql(candidates);

if (dry) {
  console.log(sql);
  process.exit(0);
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, sql, "utf8");

const target = remote ? "--remote" : "--local";
const where = staging ? "staging" : remote ? "remote" : "local";
console.log(
  `Seeding ${candidates.length} candidate(s) into ${DB_NAME} (${where})${
    prune ? " with --prune" : ""
  }...`,
);

const proc = Bun.spawnSync({
  // `process.execPath` is the bun binary itself. Spawning "bunx" directly fails on
  // Windows, where it is a shim script rather than an executable.
  cmd: [
    process.execPath,
    "x",
    "wrangler",
    "d1",
    "execute",
    DB_NAME,
    target,
    "--config",
    WRANGLER_CONFIG,
    ...ENV_FLAGS,
    "--file",
    OUT_FILE,
    ...(remote ? ["--yes"] : []),
  ],
  cwd: PKG_ROOT,
  stdio: ["inherit", "inherit", "inherit"],
});

if (proc.exitCode !== 0) {
  console.error(`\nwrangler exited with code ${proc.exitCode}.`);
  // Almost always a missing table: seeding a database that was never migrated.
  const migrate = staging ? "migrate:staging" : local ? "migrate:local" : "migrate:remote";
  console.error(`If the table is missing, run \`bun run ${migrate}\` first.`);
  process.exit(proc.exitCode ?? 1);
}

console.log("Seed applied.");
